enum STATUS_LEVEL
{
	BLOQUEADO,
	COMPLETO, 
	DESBLOQUEADO
}

globalvar info_leveis; 
info_leveis = [
	STATUS_LEVEL.DESBLOQUEADO, 
	STATUS_LEVEL.DESBLOQUEADO,
	STATUS_LEVEL.DESBLOQUEADO, 
	STATUS_LEVEL.BLOQUEADO,
	STATUS_LEVEL.BLOQUEADO,
	STATUS_LEVEL.BLOQUEADO,
	STATUS_LEVEL.BLOQUEADO,
	STATUS_LEVEL.BLOQUEADO,
	STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	//STATUS_LEVEL.BLOQUEADO,
	
];